/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Os69WTWAEFZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
export function termsncond() {
  return (
    <div className="p-4 bg-white">
      <section className="max-w-4xl mx-auto">
        <h1 className="text-center text-xl font-bold mb-4">SAAS SERVICES ORDER FORM</h1>
        <div className="border border-black p-4 mb-4">
          <div className="grid grid-cols-2 gap-4 mb-4">
            <div>
              <label className="block font-bold">Customer:</label>
              <input type="text" className="w-full border border-black" />
            </div>
            <div>
              <label className="block font-bold">Contact:</label>
              <input type="text" className="w-full border border-black" />
            </div>
            <div>
              <label className="block font-bold">Address:</label>
              <input type="text" className="w-full border border-black" />
            </div>
            <div>
              <label className="block font-bold">Phone:</label>
              <input type="text" className="w-full border border-black" />
            </div>
            <div>
              <label className="block font-bold">E-Mail:</label>
              <input type="text" className="w-full border border-black" />
            </div>
          </div>
          <div className="mb-4">
            <label className="block font-bold">Services:</label>
            <p className="border border-black p-2">
              Arvo is an information retrieval and data management tool for researchers. Allowing researchers to search
              local and online databases for information.
            </p>
          </div>
          <div className="grid grid-cols-2 gap-4 mb-4">
            <div>
              <label className="block font-bold">Services Fees:</label>
              <p className="border border-black p-2">
                $20 per user per month, payable in advance, subject to the terms of Section 4 herein.
              </p>
            </div>
            <div>
              <label className="block font-bold">Initial Service Term:</label>
              <p className="border border-black p-2">5 years</p>
            </div>
          </div>
          <div className="mb-4">
            <label className="block font-bold">Service Capacity:</label>
            <p className="border border-black p-2">One User at a time</p>
          </div>
          <div className="mb-4">
            <label className="block font-bold">Pilot Use:</label>
            <p className="border border-black p-2">
              If Services use during the Pilot Period will be restricted to non-productive evaluation use. If so, then,
              notwithstanding anything else, in connection with such pilot/evaluation use (1) no fees will apply, except
              for any Pilot Use Fee specified below, (2) the Services are provided “AS IS” and no warranty obligations
              of Company will apply, and (3) Customer may terminate this Agreement and all of its rights hereunder by
              providing Company written notice thereof no less than 10 days prior to the end of the Pilot Period;
              otherwise, this Agreement shall continue in effect for the Initial Service Term (subject to earlier
              termination as provided in the Agreement).
            </p>
          </div>
          <div className="grid grid-cols-2 gap-4 mb-4">
            <div>
              <label className="block font-bold">Pilot Period:</label>
              <p className="border border-black p-2">Thirty days</p>
            </div>
            <div>
              <label className="block font-bold">Pilot Use Fee:</label>
              <p className="border border-black p-2">0$</p>
            </div>
          </div>
        </div>
        <h1 className="text-center text-xl font-bold mb-4">SAAS SERVICES AGREEMENT</h1>
        <div className="border border-black p-4">
          <p className="mb-4">
            This SaaS Services Agreement (“Agreement”) is entered into on this ____ day of ________, 2015 (the
            “Effective Date”) between Arvo A.I. Ltd. with a place of business at 252 Braebrook, Pointe-Claire H9R 1V9
            (“Company”), and the Customer listed above (“Customer”). This Agreement includes and incorporates the above
            Order Form, as well as the attached Terms and Conditions and contains, among other things, warranty
            disclaimers, liability limitations and use limitations. There shall be no force or effect to any different
            terms of any related purchase order or similar form even if signed by the parties after the date hereof.
          </p>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block font-bold">[Company, Inc.]:</label>
              <div className="border border-black p-2 h-16" />
              <label className="block font-bold">By:</label>
              <input type="text" className="w-full border border-black" />
            </div>
            <div>
              <label className="block font-bold">[Customer]:</label>
              <div className="border border-black p-2 h-16" />
              <label className="block font-bold">By:</label>
              <input type="text" className="w-full border border-black" />
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
